active_plan: "Silent (fanless)"
plans:
  - name: "Silent (fanless)"
    plan: "silent"
    cpu_curve: "30c:0%,40c:0%,50c:0%,60c:0%,70c:31%,80c:49%,90c:56%,100c:56%"
    gpu_curve: "30c:0%,40c:0%,50c:0%,60c:0%,70c:34%,80c:51%,90c:61%,100c:61%"
  - name: "Silent (low-speed fan)"
    plan: "silent"
    cpu_curve: "30c:0%,40c:5%,50c:10%,60c:10%,70c:31%,80c:49%,90c:56%,100c:56%"
    gpu_curve: "30c:0%,40c:5%,50c:10%,60c:10%,70c:34%,80c:51%,90c:61%,100c:61%"
  - name: "Silent (default fan speed)"
    plan: "silent"
  - name: "Windows"
    plan: "windows"
  - name: "Performance"
    plan: "performance"
  - name: "Turbo"
    plan: "turbo"
